Integrating addbot
cornell-cup/cs-minibot pull request #26
Opened 2017-10-24 00:41 UTC by leotrj

2017-10-24 00:52 UTC, ScottSWu commented on gui/main.py
>              print("[ERROR] Bot not detected when trying to send script.")
Use `import logging`

2017-10-24 16:27 UTC, chynu requested changes
Would appreciate if you could add a bit of a description in the PR message, such as how successful your tests have been with add bot, what's next, etc. :0

2017-10-24 16:27 UTC, chynu commented on gui/static/js/components/addbot.js
> +        Updates list of discoverable bots
jsdoc syntax !
```JavaScript
/**
 * Updates list of discoverable bots onto front-end dropdown.
 * @param {Object.<string>} data Array of data which contains IPs of discovered bots.
 */
redoDiscoverList(data) {
  // ...
}
```

2017-10-24 16:27 UTC, chynu commented on gui/static/js/components/addbot.js
> +        var _this = this;
Can we do `const _this = this;` because `var` is uncomfy especially since it's used practically everywhere

2017-10-24 16:27 UTC, chynu commented on gui/static/js/components/addbot.js
>              //Trim the forward-slash
Is this comment no longer relevant then?

2017-10-25 18:09 UTC, chynu approved these changes

2017-10-25 18:26 UTC, merged